function [fitresult, gof] = createFit(xdata, ydata2, plotfig)
%CREATEFIT(XDATA,YDATA2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : xdata
%      Y Output: ydata2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-May-2019 17:11:16


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( xdata, ydata2 );

% Set up fittype and options.
ft = fittype( 'a/(b+exp(-c*x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
% opts.StartPoint = [0.655740699156587 0.0357116785741896 0.849129305868777];
% opts.StartPoint = [0.353486683703053 0.505893264765382 0.443519646738913];
% opts.StartPoint = [0.1 0.3 0.5];

% Fit model to data.
warning('off','all')
[fitresult, gof] = fit( xData, yData, ft, opts );
warning('on','all')

% Plot fit with data.
if plotfig && gof.rsquare>0.5
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'ydata2 vs. xdata', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel xdata
ylabel ydata2
grid on
end


