function Hd = temptemp
%TEMPTEMP Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 11-Oct-2016 16:41:45
%%
N = 12;  % Order

% Frequency Vector
F = [0 10.^(-2:0.1:-1) 1];

% Amplitude Vector
A = [1*ones(1,8) 2 4 8 16 16];
figure(1)
loglog(F,A,'.-');

h = fdesign.arbmag('N,F,A', N, F, A);

Hd = design(h, 'freqsamp');

freqz(Hd)


