function [FeatureNames]=MakeFeaturesList(BBs)
%% Populate the feature names variable
% this is a list of all the attribute curently returned
% this function also creates variables for each item in this list, so if 
% you add to this list, a variable of added name will be created back in
% the caler function, and initialised as nan(BBs,1);

FeatureNames = {  
    %'M1';'M2';'M3';'M4';'M5';... % used in testing only
    % Ratios
    'Ti_Ttot';...
    'VTi_VTe';...
    'VTi_VT';...  % VTi/VT where VT=(VTi*Te+VTe*Ti)/(Ti + Te)
    'VTe_VT';...  % VTe/VT
    'MIF_PIF';... %	MIF / PIF, after normalising, this is simply mean inspiratory flow
    'PIF_MIF';... % PIF / MIF, as used by Kaplan
     %'MIF_VT';... %	MIF / VT 
     %'PIF_VT';... %	PIF / VT
     %'PEF_VT';... %	PEF / VT
     % Flattening 
    'Ali_InspFlat';... % AUC of abs((0.1*inspT to 0.9*inspT) - MIF) /Ti
    'Ali_ExpFlat';... % AUC of abs((0.2*expT to 0.8*expT) - MEF) / Te
    'Ali_InspExpFlat';... %insp flat index / exp flat index
    'AA_InspFlat9020';... %sum(FlowInsp>0.9)/sum(FlowInsp>0.2);
    'AA_InspFlat8020';...
    'AA_InspFlat7020';...
    'AA_InspFlat6020';...
    'AA_InspFlat5020';...
    'AA_InspFlat90Ti';... %sum(FlowInsp>0.9)/sum(InspFlow);
    'AA_InspFlat80Ti';...
    'AA_InspFlat70Ti';...
    'AA_InspFlat60Ti';...
    'AA_InspFlat50Ti';...
    'AA_ExpFlat9020';... %sum(FlowExp>0.9)/sum(FlowExp>0.2);
    'AA_ExpFlat8020';...
    'AA_ExpFlat7020';...
    'AA_ExpFlat6020';...
    'AA_ExpFlat5020';...
    'AA_ExpFlat90Te';... %sum(FlowExp>0.9)/sum(ExpFlow);
    'AA_ExpFlat80Te';...
    'AA_ExpFlat70Te';...
    'AA_ExpFlat60Te';...
    'AA_ExpFlat50Te';...
    %'AA_ExpFlat';... % sum(FlowExp>0.85)/sum(FlowExp>0.4);
    'MIF50';...
    'MEF50';...
    'Teschler';... % partly flatness, partly curve fitting
    'SS_Area';... using peaks in insp thirds, find the area between peaks chord and flow trace
    % Template
    'SinI';... %Sine fit to inspiration
    'SinI50';... %Sine fit to middle 50% of inspiratory time, Clark 1998.
    'SinE';... %Sine fit to expiration
    'InvParabI';...
    'EllipseI';...
    'HypcosI';...
    % Asymmetry 
    'AsymIndex';...
    'SkewDistInsp';...
    'KurtDistInsp';...
    'SkewDistExp';...
    'KurtDistExp';...
    'AsymmetryInsp';...
    'AsymmetryExp';...
    'KurtDataInsp';...
    'KurtDataExp';...
    % Curve fitting
     %'MansourFL';... %slope of polyfit at max flow (+ve = NIFL, -ve = IFL)
     %'MansourRUA';... % flow at min/max slope, and constant C from polynomial
     %'Wiriyaporn';... % potentially skip this?
    % I:E measures
    'Ti_Te';...
    'PIF_PEF';... %	peak insp flow / peak exp flow
    'MIF_MEF';... % MIF / MEF
    'MIF50_MEF50';... % mean insp flow for middle 50% / MEF50
    'SeriesIEflow';... % ratio of insp flow to exp flow at mid volumes, (<0.97)
    'SeriesIEtime';... % ratio of insp time to exp time at mid volumes
    %'SeriesIEvol'; ... % ratio of insp vol to exp volume at mid time
    'KaplanIEvol';... % ratio of insp vol to exp vol at mid times
    % others
    %'TAA';...
    'TTran_i_Ti';...
    'TTran_i_Ttot';...
    'TTran_e_Te';...
    'TTran_e_Ttot';...
    'MorgensVPIFVTi';... % VTi at PIF / VTi, with flow norm'd to peak flow
    %'MorgensV05';... % VTi at one half Ti, with flow normalized to peak flow
    'MorgensV03';... % VTi at one third Ti, with flow normalized to peak flow
    % RiseDwellFall measures
    'FTi';... % Inspiratory Fall Time, from last 90% max flow to zero flow
    'RTi';... % Inspiratory Rise Time, from zero flow to first 90% max flow
    'DTi';... % Inspiratory Dwell Time, time from fist to last 90% max flow
    'FTe';... %
    'RTe';... %
    'DTe';... %
    % cf to reference
    %'MooneyTi';...         % removed by DLM, non-normalized value
    %'MorrisTPEF_Te';...    % removed by DLM, same as TpeakE_Te(i)
    'ATS_VPEF_VTe';...
    % flutter power (in various ranges)
    'InspFlutPowOrig';...
    'ExpFlutPowOrig';...
    'InspExpFlutPowOrig'; ...
    'InspExpFlutPowOrig_Sum'; ...
    %'InspFlutPow_VT2';...
    %'ExpFlutPow_VT2';...
    'InspFlutPow4to7';...
    'ExpFlutPow4to7';...
    'InspExpFlutPow4to7';...
    'InspExpFlutPow4to7_Sum';...
    'InspFlutPow8to12';...
    'ExpFlutPow8to12';...
    'InspExpFlutPow8to12';...
    'InspExpFlutPow8to12_Sum';...
    % DLM Flutter methods
    %'InspFlutPow4to7DLM';...
    %'ExpFlutPow4to7DLM';...
    %'InspExpFlutPow4to7DLM';...
    %'InspFlutPow8to12DLM';...
    %'ExpFlutPow8to12DLM';...
    %'InspExpFlutPow8to12DLM';...
    % Ali peaks, and peak derived measures
    %'Vpeak1_Vpeak';... % peak one / peak insp flow.
    %'Vpeak2_Vpeak';... % peak two / peak insp flow
    %'Vpeak3_Vpeak';... % peak three / peak insp flow
    'TpeakI_Ti';... %	Time to insp peak / insp time
    %'Tpeak1_Ti';... %	Time to insp peak one / insp time
    %'Tpeak2_Ti';... %	Time to insp peak two / insp time
    %'Tpeak3_Ti';... %	Time to insp peak three / insp time
    'TpeakE_Te';... %	Time to exp peak / exp time
    'TpeakI_TpeakE';... %	Time to insp peak / time to exp peak
    %'MostPromPeakW';... %	Width of the MostProminentPeak
    'MPPW_Ti';...   %   Width of MostProminentPeak / insp time
    %'PkProm1_n';... %	peak one / PromMostProminentPeak
    %'PkProm2_n';... %	peak two / PromMostProminentPeak
    %'PkProm3_n';... %	peak three / PromMostProminentPeak
    % Ali NED, this is an extension to each of the peaks measures
    'Ali_NED';... %100*(Flow(round(peakFlow_idx*Fs))-min(Flow(NEDMinValIdx)))/Vpeak;
    % AA peaks, and peak derived measures
    %'AA_NumOfPeaks';... %	Number of peaks in insp. Insp split into thirds, and peaks searched in each third. Range 1-3.
    %'AA_Pf_1_3';... %	Flow at peak 1, if a peak in thefirst third of insp exists
    %'AA_Pf_2_3';... %	Flow at peak 2, if a peak in the middle third of insp exists
    %'AA_Pf_3_3';... %	Flow at peak 3, if a peak in the last third of insp exists
    %'AA_IsTerminalPeak';... %	Is peak 3 the largest?
    %'AA_PeaksRatio';... %	sum(P./max(P))/3; where P=[p1 p2 p3]. 
    % Will be 0.3333 if only one peak. % removed by DLM, non-monotonic
    % AA NED, this is an extension to each of the peaks measures
    'AA_NED';... % Reduction in peak (choice of three) from the flow value at BrMid/2
    % AA Expiratory flow limitation indices
    %'AA_EFLI';...
    % discontinuity
    %'D1';...
    %'D2';...
    %'D3';...
    %'D4';...
    %'MinFlowChange';...
    %'MedianFlowChange';...
    %'STDFlowChange';...
    };

% as a way of preventing possible human errors, the variables based upon
% these are automatically enumerated from the FeaturesNames list
for ft = 1:length(FeatureNames)
    % initialise a variable of name "FeaturesNames(ft)" as nan(BBs,1);
    str = char(FeatureNames(ft));
    assignin('caller', str, nan(BBs,1)); % make them back in the caller Fn
end

end

%% The loop above essentially replaces the following 
% Initialise variables for every item in the list
% Ti_Te = nan(BBs,1);
% Ti_Ttot = nan(BBs,1);
% VTi_VTe = nan(BBs,1);
% VTi_VT = nan(BBs,1);
% etc...

