FROM rocker/r-ver:4.2.1

# Updates the base image with a couple of libraries that are required by Shiny and related R packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo \
    libcurl4-gnutls-dev \
    libcairo2-dev \
    libxt-dev \
    libssl-dev \
    libssh2-1-dev \
    && rm -rf /var/lib/apt/lists/*

RUN install2.r shiny
RUN echo "local({options(shiny.port = 3838, shiny.host = '0.0.0.0')})" > /usr/local/lib/R/etc/Rprofile.site
RUN addgroup --system app && adduser --system --ingroup app app

WORKDIR /home/app
COPY app.R nsrr-viz.RData .
COPY viz ./viz
RUN chown app:app -R /home/app
USER app
EXPOSE 3838
CMD ["R", "-e", "shiny::runApp('/home/app')"]
