function [fitresult, gof] = fitAxPowerB(x, y,Brange)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Feb-2020 11:33:49


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
%opts.Robust = 'Bisquare';
opts.StartPoint = [42.5892669335796 -0.215498693085632];
if exist('Brange')
    opts.Lower=[-Inf Brange(1)];
    opts.Upper=[Inf Brange(2)];
end

% Fit model to data.
[fitresult, gof,output] = fit( xData, yData, ft, opts );


% Plot fit with data.

%h = scatter(xData, yData,15,[0.2 0.5 0.6],'filled','markerfacealpha',0.3);
%legend( h, 'y vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%hold on
%h = plot(fitresult);


if 1 %run outlier analysis and repeat
outlierF = 3;
figure(76); clf(76); set(gcf,'color',[1 1 1]);
subplot(2,1,1);
temp = output.residuals;
thresU = outlierF*diff(prctile(temp,[50 90])) + prctile(temp,[50]);
thresL = prctile(temp,[50]) - outlierF*diff(prctile(temp,[10 50]));
I = temp<thresU & temp>thresL;
sum(I)
[fitresult, gof,output] = fit( xData(I), yData(I), ft, opts );
% Plot fit with data.
%delete(h);

maxy = 1.1*max(yData(I));
yData(yData>maxy)=maxy;

h1 = scatter(xData(~I), yData(~I),10,[0.9 0.3 0.2],'filled','markerfacealpha',0.5);
hold on
h2 = scatter(xData(I), yData(I),10,[0.2 0.5 0.6],'filled','markerfacealpha',0.6);
h = plot(fitresult);
set(gca,'tickdir','out')
hold off
legend('off')
subplot(2,1,2);
ytemp = yData.^(1/fitresult.b);
ytemp = nanmedian(yData)./nanmedian(ytemp).*ytemp;
h1 = scatter(xData(~I), ytemp(~I),10,[0.9 0.3 0.2],'filled','markerfacealpha',0.5);
hold on
h2 = scatter(xData(I), ytemp(I),10,[0.2 0.5 0.6],'filled','markerfacealpha',0.6);
hold off
legend('off')

end 


