% This allows you to correct the volume minimums

function interactive_vmin2(vol, flowFig, ivmin, vmin, n, l)
%CREATEFIGURE(vol,ivmin,vmin)
%  vol:  vector of y data
%  ivmin:  vector of x data
%  vmin:  vector of y data
 
%  Auto-generated by MATLAB on 21-Aug-2007 12:18:10
 
% Create figure
scrsz = get(0,'ScreenSize');
figure1 = figure('Position',[10 70 scrsz(3)-20 scrsz(4)-200]);
 
% Create axes
axes1 = axes('Parent',figure1);
axis([n n+l min(vol)-1 max(vol)+.5]);
box('on');
hold('all');

plot1 = plot([n n+l],[0 0]);

% Create plot
% plot2 = plot(vol);

 
% Create plot
plot3 = plot(...
  ivmin,flowFig(ivmin),...
  'LineStyle','none',...
  'Marker','.',...
  'MarkerSize',15,...
  'MarkerEdgeColor',[0 0.498 0],...
  'MarkerFaceColor',[0 0.498 0]);

plot4 = plot(flowFig);