library(luna)
k <- ldb("/Users/sq566/Desktop/saps/stages_spanning.db")
png(file="/Users/sq566/Desktop/saps/STAGES-SPANNING.png", height=800, width=1600, res=100)
par(mar = c(4,4,4,4))
site <- substr(k$SPANNING$BL$ID, start = 1, stop = 4)
plot(k$SPANNING$BL$SPANNED_PCT, col = as.factor(site), pch=16 , ylab="SPANNED_PCT" , xlab="Individual", cex = 0.8)
legend("bottomleft", legend=levels(as.factor(site)), col=1:14, pch=16)
title(main = "STAGES / SPANNING / Orignial Annotations", cex.main = 1)
dev.off()
